// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2_OLA6FNNEh7BrFIOWxa-B86HEi1z3jE',
    appId: '1:694880629233:web:29e2d6abe7e8faf4211450',
    messagingSenderId: '694880629233',
    projectId: 'old-ephraim',
    authDomain: 'old-ephraim.firebaseapp.com',
    storageBucket: 'old-ephraim.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY0BKCdKcgpxR42oWKbCWadunNOqjWo4w',
    appId: '1:694880629233:android:d761c138e105ec06211450',
    messagingSenderId: '694880629233',
    projectId: 'old-ephraim',
    storageBucket: 'old-ephraim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxh-56wMJvAftnL9Pitt45L6mxKaVIDho',
    appId: '1:694880629233:ios:ec3471a1cf5782d4211450',
    messagingSenderId: '694880629233',
    projectId: 'old-ephraim',
    storageBucket: 'old-ephraim.appspot.com',
    iosClientId: '694880629233-lnt829apf8cneu3eid821adciqdokdsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.oldEphraimApp',
  );
}
